### ISSUE TITLE
Running sever in production ENV with craco start

### ISSUE THREAD

**Issue by satendra02** [gsoft-inc/craco#174]
Here is the full error log on running below command. I using latest version **5.6.4**  

**$ NODE_ENV=production craco start**

Please have a look

```
/Users/satendra/workspace/recast-app/node_modules/@craco/craco/lib/plugin-utils.js:29
    throw new Error(
    ^

Error: Found an unhandled loader in the production webpack config: /Users/satendra/workspace/recast-app/node_modules/style-loader/index.js

This error probably occurred because you updated react-scripts or craco. Please try updating craco-less to the latest version:

   $ yarn upgrade craco-less

Or:

   $ npm update craco-less

If that doesn't work, craco-less needs to be fixed to support the latest version.
Please check to see if there's already an issue in the FormAPI/craco-less repo:

   * https://github.com/FormAPI/craco-less/issues?q=is%3Aissue+webpack+unknown+rule

If not, please open an issue and we'll take a look. (Or you can send a PR!)

You might also want to look for related issues in the craco and create-react-app repos:

   * https://github.com/sharegate/craco/issues?q=is%3Aissue+webpack+unknown+rule
   * https://github.com/facebook/create-react-app/issues?q=is%3Aissue+webpack+unknown+rule

    at throwUnexpectedConfigError (/Users/satendra/workspace/recast-app/node_modules/@craco/craco/lib/plugin-utils.js:29:11)
    at throwError (/Users/satendra/workspace/recast-app/node_modules/craco-less/lib/craco-less.js:14:5)
    at /Users/satendra/workspace/recast-app/node_modules/craco-less/lib/craco-less.js:119:7
    at Array.forEach (<anonymous>)
    at Object.overrideWebpackConfig (/Users/satendra/workspace/recast-app/node_modules/craco-less/lib/craco-less.js:51:11)
    at overrideWebpack (/Users/satendra/workspace/recast-app/node_modules/@craco/craco/lib/features/plugins.js:42:40)
    at /Users/satendra/workspace/recast-app/node_modules/@craco/craco/lib/features/plugins.js:64:29
    at Array.forEach (<anonymous>)
    at applyWebpackConfigPlugins (/Users/satendra/workspace/recast-app/node_modules/@craco/craco/lib/features/plugins.js:63:29)
    at mergeWebpackConfig (/Users/satendra/workspace/recast-app/node_modules/@craco/craco/lib/features/webpack/merge-webpack-config.js:67:30)
```

> **Note:** The log suggests to update **craco-less** but the issue still exists.

**Comment by patricklafrance** [comment]
Hi @satendra02 

Have you tryed posting the issue on https://github.com/DocSpring/craco-less repository? Seems related to the plugin not to the core of CRACO.
