### ISSUE TITLE
[Build Failed] error errno ENOENT

### ISSUE THREAD

**Issue by EggTronic** [gsoft-inc/craco#189]
Hi, I failed to build react app on my remote Linux instance with Graco.
I can build without problem on my windows PC.

Here is the error information
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle smart-shower-frontend@0.1.0~prebuild: smart-shower-frontend@0.1.0
6 info lifecycle smart-shower-frontend@0.1.0~build: smart-shower-frontend@0.1.0
7 verbose lifecycle smart-shower-frontend@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle smart-shower-frontend@0.1.0~build: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/Smart-Shower-App/smart-shower-frontend/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle smart-shower-frontend@0.1.0~build: CWD: /root/Smart-Shower-App/smart-shower-frontend
10 silly lifecycle smart-shower-frontend@0.1.0~build: Args: [ '-c', 'craco build' ]
11 info lifecycle smart-shower-frontend@0.1.0~build: Failed to exec build script
12 verbose stack Error: smart-shower-frontend@0.1.0 build: 
`craco build`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)       
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid smart-shower-frontend@0.1.0
14 verbose cwd /root/Smart-Shower-App/smart-shower-frontend15 verbose Linux 5.4.0-42-generic
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
17 verbose node v10.19.0
18 verbose npm  v6.14.4
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error smart-shower-frontend@0.1.0 build: `craco build`
23 error spawn ENOENT
24 error Failed at the smart-shower-frontend@0.1.0 build script.
24 error This is probably not a problem with npm. There is likely additiona
```

**Comment by EggTronic** [comment]
It looks like I was running out of memory
