### ISSUE TITLE
TypeError: rules.some is not a function

### ISSUE THREAD

**Issue by vjpr** [gsoft-inc/craco#200]
```
[watch-cra] /xxx/node_modules/.pnpm/@craco/craco@5.6.4_react-scripts@3.4.1/node_modules/@craco/craco/lib/loaders.js:34
[watch-cra]     rules.some((rule, index) => {
[watch-cra]           ^
[watch-cra]
[watch-cra] TypeError: rules.some is not a function
[watch-cra]     at getLoaderRecursively (/xxx/node_modules/.pnpm/@craco/craco@5.6.4_react-scripts@3.4.1/node_modules/@craco/craco/lib/loaders.js:34:11)
[watch-cra]     at /xxx/node_modules/.pnpm/@craco/craco@5.6.4_react-scripts@3.4.1/node_modules/@craco/craco/lib/loaders.js:39:26
[watch-cra]     at Array.some (<anonymous>)
[watch-cra]     at getLoaderRecursively (/xxx/node_modules/.pnpm/@craco/craco@5.6.4_react-scripts@3.4.1/node_modules/@craco/craco/lib/loaders.js:34:11)
[watch-cra]     at /xxx/node_modules/.pnpm/@craco/craco@5.6.4_react-scripts@3.4.1/node_modules/@craco/craco/lib/loaders.js:41:26
[watch-cra]     at Array.some (<anonymous>)
[watch-cra]     at getLoaderRecursively (/xxx/node_modules/.pnpm/@craco/craco@5.6.4_react-scripts@3.4.1/node_modules/@craco/craco/lib/loaders.js:34:11)
[watch-cra]     at getLoader (/xxx/node_modules/.pnpm/@craco/craco@5.6.4_react-scripts@3.4.1/node_modules/@craco/craco/lib/loaders.js:54:28)
[watch-cra]     at Object.overrideWebpackConfig (/xxx/node_modules/.pnpm/craco-less@1.17.0_5d443e742fa91091789af07143985304/node_modules/craco-less/lib/craco-less.js:131:47)
[watch-cra]     at overrideWebpack (/xxx/node_modules/.pnpm/@craco/craco@5.6.4_react-scripts@3.4.1/node_modules/@craco/craco/lib/features/plugins.js:42:40)
```

Should there be a guard against this...or I am doing something wrong...

**Comment by vjpr** [comment]
`Rule.use` must be an array or a function https://webpack.js.org/configuration/module/#ruleuse

```
const {getLoaders, loaderByName, addBeforeLoaders} = require('@craco/craco')

module.exports = {
  overrideWebpackConfig: ({
    webpackConfig,
    cracoConfig,
    pluginOptions,
    context: {env, paths},
  }) => {
    const loader = {
      test: /\.js$/,
      include: /node_modules\/react-data-grid\/lib/,
      use: [{ // <--- `use` needs to be an array or craco breaks.
        loader: require.resolve('babel-loader'),
        options: {
          presets: ['@foo/babel-preset-react', {}],
        },
      }],
    }
    addBeforeLoaders(webpackConfig, loaderByName('babel-loader'), loader)
    return webpackConfig
  },
}

```
