### ISSUE TITLE
Error: Callback was already called.

### ISSUE THREAD

**Issue by floviolleau** [gsoft-inc/craco#259]
Hi,

I have a small issue.

When I run start, all is good and the page opens in my browser.

If I modify some code in my src folder, the start suddenly fail with this error:
```bash
demoApplication\node_modules\neo-async\async.js:16
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (C:\P4V\uxf-new\2-dist\demoApplication\node_modules\neo-async\async.js:16:11)
    at C:\P4V\uxf-new\2-dist\demoApplication\node_modules\neo-async\async.js:2818:7
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I need to manually restart the start and it takes time for each modification.

<details>
  <summary>Here is my craco config (click to expand)</summary>

```javascript
const PATH = require('path');
const FS = require('fs');
const express = require('express');
const SpeedMeasurePlugin = require('speed-measure-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const evalSourceMapMiddleware = require('react-dev-utils/evalSourceMapMiddleware');
const errorOverlayMiddleware = require('react-dev-utils/errorOverlayMiddleware');

const someExternals = require('some-external-module/sdk.externals');

const PACKAGE_JSON = require('./package.json');
const ROOT_PATH = PATH.resolve(__dirname);
const TEMPLATE_PATH = PATH.resolve(ROOT_PATH, 'template');
const DIST_FOLDER = PATH.resolve(ROOT_PATH, 'dist');

// Webpack modes
const MODES = {
    NONE: 'none',
    PRODUCTION: 'production',
    DEVELOPMENT: 'development'
};

const resolveModulePath = (moduleName) => {
    return PATH.dirname(require.resolve(`${moduleName}/package.json`));
};

let resources = {
    '.': 'public',
    './static/js/resources/scripts': 'resources/scripts',
    './static/js/resources/some-external-module/dist': PATH.resolve(
        resolveModulePath('some-external-module'),
        'dist'
    ),
    './static/js/resources/some-external-css-style-module/dist': PATH.resolve(resolveModulePath('some-external-css-style-module'), 'dist')
};

module.exports = {
    reactScriptsVersion: 'react-scripts' /* (default value) */,
    webpack: {
        configure: (webpackConfig, {env, paths}) => {
            const measureBuildSpeed = true;

            // change output folder
            webpackConfig.output.path = DIST_FOLDER;
            webpackConfig.output.libraryTarget = 'umd';

            paths.appBuild = DIST_FOLDER;
            paths.appHtml = PATH.resolve(TEMPLATE_PATH, 'index.html.js');

            //-------------------
            // EXTERNALS
            //-------------------
            const EXTERNALS = {
                // react: 'React',
                // 'react-dom': 'ReactDOM',
                react: {root: 'React', commonjs2: 'react', commonjs: 'react', amd: 'react'},
                'react-dom': {root: 'ReactDOM', commonjs2: 'react-dom', commonjs: 'react-dom', amd: 'react-dom'},
                ...someExternals
            };

            if (webpackConfig.externals) {
                webpackConfig.externals = Object.assign(webpackConfig.externals, EXTERNALS);
            } else {
                webpackConfig.externals = EXTERNALS;
            }

            //-------------------
            // CONFIGURATION
            //-------------------
            const REACT_FILE = `react.${env === MODES.DEVELOPMENT ? 'development' : 'production.min'}.js`;
            const REACT_DOM_FILE = `react-dom.${env === MODES.DEVELOPMENT ? 'development' : 'production.min'}.js`;

            resources = {
                './static/js/resources/react/umd': PATH.resolve(resolveModulePath('react'), `umd/${REACT_FILE}`),
                './static/js/resources/react-dom/umd': PATH.resolve(
                    resolveModulePath('react-dom'),
                    `umd/${REACT_DOM_FILE}`
                ),
                ...resources
            };

            const HEAD = [
                PATH.posix.join(
                    paths.publicUrlOrPath,
                    'static/js/resources/some-external-css-style-module/dist/css/style.css'
                )
            ];

            const BODY = [
                PATH.posix.join(paths.publicUrlOrPath, `static/js/resources/react/umd/${REACT_FILE}`),
                PATH.posix.join(paths.publicUrlOrPath, `static/js/resources/react-dom/umd/${REACT_DOM_FILE}`),
                PATH.posix.join(paths.publicUrlOrPath, 'static/js/resources/scripts/react-parent-pointers.js'),
                PATH.posix.join(
                    paths.publicUrlOrPath,
                    'static/js/resources/some-external-module/dist/some-external-module.js'
                )
            ];

            //-------------------
            // PLUGINS
            //-------------------
            // override template
            webpackConfig.plugins = webpackConfig.plugins.map((plugin) => {
                if (plugin.constructor.name === 'HtmlWebpackPlugin') {
                    if (env === 'development') {
                        plugin = new HtmlWebpackPlugin({
                            inject: true,
                            template: PATH.resolve(TEMPLATE_PATH, 'index.html.js'),
                            filename: 'index.html',
                            title: PACKAGE_JSON.name,
                            publicPath: paths.publicUrlOrPath,
                            scripts: {
                                head: HEAD,
                                body: BODY
                            },
                            // client libs declaration
                            clientLibsDeclaration: {
                                path: PATH.resolve(DIST_FOLDER, 'client-libs.json')
                            }
                        });
                    } else {
                        plugin = new HtmlWebpackPlugin({
                            inject: true,
                            template: PATH.resolve(TEMPLATE_PATH, 'index.html.js'),
                            filename: 'index.html',
                            title: PACKAGE_JSON.name,
                            publicPath: paths.publicUrlOrPath,
                            scripts: {
                                head: HEAD,
                                body: BODY
                            },
                            minify: {
                                removeComments: true,
                                collapseWhitespace: true,
                                removeRedundantAttributes: true,
                                useShortDoctype: true,
                                removeEmptyAttributes: true,
                                removeStyleLinkTypeAttributes: true,
                                keepClosingSlash: true,
                                minifyJS: true,
                                minifyCSS: true,
                                minifyURLs: true
                            },
                            // client libs declaration
                            clientLibsDeclaration: {
                                path: PATH.resolve(DIST_FOLDER, 'client-libs.json')
                            }
                        });
                    }
                }

                return plugin;
            });

            const PLUGINS = [
                new CopyWebpackPlugin({
                    patterns: Object.entries(resources).map(([dest, src]) => {
                        return {
                            from: src,
                            to: PATH.resolve(DIST_FOLDER, dest)
                        };
                    })
                })
            ];
            if (webpackConfig.plugins) {
                webpackConfig.plugins.push(...PLUGINS);
            } else {
                webpackConfig.plugins = PLUGINS;
            }

            //-------------------
            // SPEED MEASUREMENT
            //-------------------
            const smp = new SpeedMeasurePlugin({
                disable: !measureBuildSpeed,
                outputFormat: 'humanVerbose'
            });

            if (measureBuildSpeed) {
                console.log('\n');
                console.log('---------------------------------');
                console.log('[SPEED] Build speed measurement');
                console.log('---------------------------------');
            }

            // console.log(webpackConfig)
            return smp.wrap(webpackConfig);
        }
    },
    devServer: (devServerConfig, {env, paths, allowedHost}) => {
        // Files served
        devServerConfig.contentBase = DIST_FOLDER;
        devServerConfig.publicPath = paths.publicUrlOrPath;

        devServerConfig.before = (app, server) => {
            // Keep `evalSourceMapMiddleware` and `errorOverlayMiddleware`
            // middlewares before `redirectServedPath` otherwise will not have any effect
            // This lets us fetch source contents from webpack for the error overlay
            app.use(evalSourceMapMiddleware(server));
            // This lets us open files from the runtime error overlay.
            app.use(errorOverlayMiddleware());

            if (FS.existsSync(paths.proxySetup)) {
                // This registers user provided middleware for proxy reasons
                require(paths.proxySetup)(app);
            }

            // Serve the styling-base on /static/js/resources/some-external-css-style-module
            app.use(
                PATH.posix.join(paths.publicUrlOrPath, 'static/js/resources/some-external-css-style-module'),
                express.static(resolveModulePath('some-external-css-style-module'))
            );
            app.use(
                PATH.posix.join(paths.publicUrlOrPath, 'static/js/resources/react'),
                express.static(resolveModulePath('react'))
            );
            app.use(
                PATH.posix.join(paths.publicUrlOrPath, 'static/js/resources/react-dom'),
                express.static(resolveModulePath('react-dom'))
            );
            app.use(
                PATH.posix.join(paths.publicUrlOrPath, 'static/js/resources/some-external-module'),
                express.static(resolveModulePath('some-external-module'))
            );
        };

        devServerConfig.proxy = [
            {
                context: ['/dist'],
                target: `http://localhost:5000/`,
                pathRewrite: {'/dist': ''}
            }
        ];

        return devServerConfig;
    }
};
```
</details>

Any ideas?

Thanks

**Comment by floviolleau** [comment]
Hi,

After leaving this annoying issue, I started again to research ... and I finally found the issue. It was because of SpeedMeasurePlugin.

If you remove it, all is back to normal now...
