### ISSUE TITLE
#microfrontends Module Federation throuble: SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by pravosleva** [gsoft-inc/craco#363]
```bash
$ craco start
(node:637644) UnhandledPromiseRejectionWarning: /home/pravosleva/projects/smartprice_projects/front.dev/dev.instructions-page-3/node_modules/craco-module-federation/index.js:27
      if (pluginOptions?.useNamedChunkIds) {
                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/pravosleva/projects/smartprice_projects/front.dev/dev.instructions-page-3/craco.config.js:1:31)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
(node:637644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:637644) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aulisius** [comment]
@pravosleva what Node.js version are you using? The optional chaining `?.` syntax is only available in node.js 14+

**Comment by pravosleva** [comment]
@aulisius thanx. Its Ok.
