### ISSUE TITLE
Object is not extensible

### ISSUE THREAD

**Issue by borgdrone7** [gsoft-inc/craco#412]
Hi,

I used cra-to-nx to convert cra app to nx. 
However when I try to serve my nx app I get this exception:

```
(node:108358) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of undefined
    at my-cra-app/apps/my-nx-app/craco.config.js:27:33
    at Array.find (<anonymous>)
    at my-cra-app/apps/my-nx-app/craco.config.js:26:41
    at Array.forEach (<anonymous>)
    at configure (my-cra-app/apps/my-nx-app/craco.config.js:24:29)
    at giveTotalControl (my-cra-app/node_modules/@craco/craco/lib/features/webpack/merge-webpack-config.js:57:25)
    at mergeWebpackConfig (my-cra-app/node_modules/@craco/craco/lib/features/webpack/merge-webpack-config.js:106:38)
    at overrideWebpackDev (my-cra-app/node_modules/@craco/craco/lib/features/webpack/override.js:11:36)
    at my-cra-app/node_modules/@craco/craco/scripts/start.js:27:5
(Use `node --trace-warnings ...` to show where the warning was created)
(node:108358) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:108358) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 1.29s.
```

So I fixed above error by adding rr.loader && rr.loader.indexOf... (since I saw that not all modules have loader and babel ones have). Now nx run myapp:serve gives me this:

```
my-cra-app/apps/my-nx-app/node_modules/react-scripts/scripts/start.js:19
throw err;
^

TypeError: Cannot add property strict, object is not extensible
at verifyTypeScriptSetup (my-cra-app/apps/my-nx-app/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:231:45)
at Object. (my-cra-app/apps/my-nx-app/node_modules/react-scripts/scripts/start.js:31:1)
at Module._compile (internal/modules/cjs/loader.js:1085:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (internal/modules/cjs/loader.js:790:12)
at Module.require (internal/modules/cjs/loader.js:974:19)
at require (internal/modules/cjs/helpers.js:101:18)
at start (my-cra-app/node_modules/@craco/craco/lib/cra.js:218:5)
at my-cra-app/node_modules/@craco/craco/scripts/start.js:30:5
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Does anyone know what could be the issue?

**Comment by dilanx** [comment]
@borgdrone7 can you share your `package.json`?

**Comment by borgdrone7** [comment]
> @borgdrone7 can you share your `package.json`?

Sorry, I don't have it anymore as I converted the project manually and the file changed significantly since.
